BUILDR-463 Setting a system property in the buildfile causes a NoClassDefFoundError
git-svn-id: https://svn.apache.org/repos/asf/buildr/trunk@959862 13f79535-47bb-0310-9956-ffa450edef68